### ISSUE TITLE
Support showing logit/tuned lens predictions in the middle of layers (e.g. after attention/before MLP)

### ISSUE THREAD

**Issue by williamrs-openai** [AlignmentResearch/tuned-lens#104]
It would be useful in figuring out when to attribute changes to MLP layer vs. attention heads. Ideally would train seperate tuned lens for intermediate residual stream, but maybe still helpful if you use the same lens as at the start of the layer.

**Comment by williamrs-openai** [comment]
Thanks for putting together the notebook

**Comment by levmckinney** [comment]
I'm glad it was helpful.

I don't think we will be adding support for training lenses on individual subcomponents in the near future. So, I'm going to mark this as resolved once #103 merges.
