### ISSUE TITLE
Can not pull the docker image, is it public?

### ISSUE THREAD

**Issue by xszheng2020** [AlignmentResearch/tuned-lens#39]
Hi, @AdamGleave 
May I ask that have you changed the docker image to public? 
It seem still private and can not be pulled?

```
docker pull ghcr.io/alignmentresearch/tuned-lens
Using default tag: latest
Error response from daemon: denied
```

**Comment by levmckinney** [comment]
Yup it needs to be made public. Working to fix this now.

**Comment by levmckinney** [comment]
It should now be public
