### ISSUE TITLE
What's 'white_box'?

### ISSUE THREAD

**Issue by dbl001** [AlignmentResearch/tuned-lens#49]
In `tuned_lens/notebooks/layer_ablation.ipynb:
```
from white_box.data import (
    chunk_and_tokenize,
    compute_nats_to_bpb_ratio,
    silence_datasets_messages
)

ModuleNotFoundError: No module named 'white_box'
```
Where do I find 
```
dataset = Dataset.from_json("/mnt/ssd-1/nora/lens-test.jsonl")
```

**Comment by levmckinney** [comment]
White box is the old name for this repository. We still need to finish refactoring the notebooks to reflect some recent refactors. I believe `lens-test.jsonl` is just the test set of the pile see the [documentation](https://tuned-lens.readthedocs.io/en/latest/tutorials/training_and_evaluating_lenses.html). Can you confirm @norabelrose?

**Comment by norabelrose** [comment]
> White box is the old name for this repository. We still need to finish refactoring the notebooks to reflect some recent refactors. I believe `lens-test.jsonl` is just the test set of the pile see the [documentation](https://tuned-lens.readthedocs.io/en/latest/tutorials/training_and_evaluating_lenses.html). Can you confirm @norabelrose?

Yes that's correct

**Comment by dbl001** [comment]
Any thoughts on device='MPS' for the GPU?

**Comment by levmckinney** [comment]
Once you install the application in should be on your path.
